services:
  - type: web
    name: pharmalert
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 app:app
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: "False"
      - key: SCHEDULER_TIMEZONE
        value: Asia/Kolkata
      - key: EXPIRY_LEAD_DAYS
        value: "30"
      - key: EMAIL_SENDER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_RECEIVER
        sync: false
      - key: TWILIO_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: RECEIVER_PHONE_NUMBER
        sync: false
